---
title: "First Knit"
author: "Your Name"
date: "Date, 2019"
output:
  pdf_document:
    toc: yes
  html_document:
    number_sections: yes
    toc: yes
---

### `r as.character(Sys.Date())`



# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. Half the points in this assignment depend on your picture and name being correct!!  Be sure to put your photo in the AAA_Owner_Info folder and call it My_photo.jpg after first renaming the current one to Koala.jpg . 

##Where are you now?  
What row are you in, front,middle or back?  Do you usually choose a similiar row in other classes? What is the computer number where you are sitting?  How on a scale of 1 to 10 (1=low, 10=high) How you feel about periodic seat re-assignment, say how and why. Teams, have you ever worked on one in a class setting?  

###my answer 

I am sitting in row four on the far left.  I usually tend to sit in the back. I don't like being told where to sit. We are all adults so chosing our seats seems like something we should be able to do without issue. I've worked on multiple group projects in a class setting.
  
   
     


##Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want me to call you something else - what would that be? 

###my answer  

I like to be called Symon (Simon).
  
   
 




##Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

###my answer     

I'm hoping to get my MBA so that I can advance further in the work place and move into a management roll eventually.
  
   
 




##Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

###my answer    

I've been to the UK specifically to Wales.  I plan on traveling to Italy and Japan.  I have never been in the military if I got drafted I would prefer the Airforce or the Navy.  I would choose either brach because I've had family in both braches.
  
   
  




##Why are you taking Math 115?  
What grade do you need to attain in stats to not upset your future plans, What is your plan?
 

###my answer     

I need to obtain a B or higher to stay on track with graduating Spring 2020.
  
   
 





##Homework Help and Getting around?  
On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  Do you have a computer you can use at home? If so, what kind is it (windows, Apple, Linux)? Do you have internet access at home?  
How do you get to class? Are there issues that limit when you can be at the college?Where and when did you attend high school?  Do you currently have a job?

###my answer   

I would rate myself as around a 6 or 7 when it comes to being computer literate. Yes, I have a windows computer and yes I also have internet access at home.  I drive myself to class, and no I don't have any issues that will limit my being in class.  I attended graduated High School in 2011.  I currently have 3 jobs. 
   
  
## critique of the AI in business article




